#!/usr/bin/env bash

# Update system packages
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create index.html with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html
# Configure the redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.merriam-webster.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart

