#!/bin/env bash

# Update system packages
apt-get update

# Install Nginx
apt-get install -y nginx

# Create index.html with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure the redirection
sed -i 's/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.merriam-webster.com permanent;/' /etc/nginx/sites-enabled/default

# Create 404.html error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Add redirect for error 404
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart

