#!/usr/bin/env bash
# Configure Nginx with its HTTP response contains a custom header
# The  custom HTTP header( X-Served-By)
# The value of the custom HTTP header must be the hostname of the server Nginx 
sudo apt-get update
sudo apt-get -y install nginx

# Firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

# makig directory
sudo mkdir -p /var/www/html

# CHMOD to allow  easy creation of files in  directory var/
sudo chmod -R 755 /var/www

#  create the index page
echo 'Hello World!' |sudo tee  /var/www/html/index.html

# webpage for error 404
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# redirect for a single page(/redirect_me) and add header to display hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the web server
sudo service nginx restart
