#!/usr/bin/env bash
# Configure Nginx - contains a custom header (on web-01 and web-02)
# The custom HTTP header must be X-Served-By
# custom HTTP header must be the hostname of the server Nginx is running on
sudo apt-get update
sudo apt-get -y install nginx

# firewall for request through port:80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# change permissions to easily create files in this directory
sudo chmod -R 755 /var/www

# the index page
echo 'Hello World!' |sudo tee  /var/www/html/index.html

# webpage for error 404
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# configure Nginx with custom response header configuration
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;

     location    /redirect_me {
         return  301 https://stackoverflow.com/;
     }

     error_page 404 /404.html;
     location   /404 {
         root   /var/www/html;
         internal;
     }

     add_header X-Served-By \$hostname;
}
" > /etc/nginx/sites-available/default


# restart the web server
sudo service nginx restart
