#!/usr/bin/env bash
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# configaration file
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

echo "
frontend frontend_http
    bind *:80
    mode http
    default_backend backend_http

backend backend_http
    mode http
    balance roundrobin
    server 199717-web-01 100.25.138.54:80 check
    server 199717-web-02 100.26.161.218:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# managing HaProxy  via an initt
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo service haproxy start

# verification of  HAProxy configs
sleep 10
curl -Is localhost | grep "Server:\|X-Served-By:"

#restart haproxy
sudo service haproxy restart
