#!/usr/bin/env bash
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Install and configure HAproxy on my lb-01 server.

# Update the system packages
sudo apt-get update

# Install HAproxy
sudo apt-get -y install haproxy

# Configure HAproxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
defaults
    mode http
    timeout connect 15s
    timeout client 40s
    timeout server 40s

frontend web-frontend
    bind *:80  
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 199717-web-01 54.236.54.87:80 check
    server 199717-web-02 52.91.127.122:80 check
EOT

# Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy service
sudo service haproxy restart

