#!/usr/bin/env bash
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# config file
server_config=\
"
frontend  kelvin-frontend
        bind *:80
        mode http
        default_backend kelvin-backend
backend kelvin-backend
        balance roundrobin
        server 199717-web-01 54.236.54.87:80 check
        server 199717-web-02 52.91.127.122:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started 
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
