#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet
awk '{sub(/8080/, "80")}1' /etc/nginx/sites-enabled/default | sudo tee /etc/nginx/sites-enabled/default >/dev/null
service nginx restart
pkill -o nginx
