#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid
# Create PID file
echo $$ > /var/run/myscript.pid

# Set signal handlers
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid && exit 0' SIGQUIT SIGTERM

# Display message indefinitely
echo "To infinity and beyond"
while true
do
	sleep 1
done
