#!/usr/bin/bash
# Script that displays the contents of `/etc/passwd`.
# displays the username, user id, and user home directory path.
file="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$file"
