#!/usr/bin/env bash
# Script to Reload Gunicorn
# ps aux | grep gunicorn | awk '{ print $2 }' | xargs kill -HUP
# 4-reload_gunicorn_no_downtime
# Find the process IDs of Gunicorn
sudo ps auxf | grep '[g]unicorn' | awk '{ print $2 }' | kill -HUP
