#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server
# using the private key ~/.ssh/school with the user ubuntu.
# Only use ssh single-character flags
ssh ubuntu@54.236.54.87 -i ~/.ssh/school
